Style/AndOr:
  EnforcedStyle: always

Style/BracesAroundHashParameters:
  Enabled: braces

Style/ClassAndModuleChildren:
  EnforcedStyle: compact
  AutoCorrect: true   

Style/HashSyntax:
  EnforcedStyle: ruby19


Layout/AlignHash:
  EnforcedColonStyle: table
  EnforcedHashRocketStyle: table

Layout/AlignParameters:
  EnforcedStyle: with_first_parameter

# Metrics
Metrics/BlockLength:
  Enabled: false